# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aflevering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='(unknown)', max_length=100, verbose_name='PDF naam')),
                ('sectie', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Sectie (optioneel)')),
                ('aflnum', models.IntegerField(db_index=True, default=0, verbose_name='Aflevering')),
                ('inleiding', models.BooleanField(default=False, verbose_name='Heeft inleiding')),
                ('toonbaar', models.BooleanField(default=True, verbose_name='Mag getoond worden')),
                ('jaar', models.IntegerField(default=1900, verbose_name='Jaar van publicatie')),
                ('auteurs', models.CharField(default='(unknown)', max_length=100, verbose_name='Auteurs')),
                ('afltitel', models.CharField(default='(unknown)', max_length=100, verbose_name='Boektitel')),
                ('sectietitel', models.CharField(blank=True, default='', max_length=100, verbose_name='Sectietitel')),
                ('plaats', models.CharField(default='(unknown)', max_length=100, verbose_name='Plaats van publicatie')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij aflevering')),
            ],
            options={
                'verbose_name_plural': 'Afleveringen',
            },
        ),
        migrations.CreateModel(
            name='Deel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='(unknown)', max_length=100, verbose_name='Volledige titel')),
                ('nummer', models.IntegerField(default=0, verbose_name='Nummer')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij dit deel')),
            ],
            options={
                'verbose_name_plural': 'Delen',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toelichting', models.TextField(blank=True, verbose_name='Omschrijving van het lemma')),
                ('bronnenlijst', models.TextField(blank=True, db_index=True, verbose_name='Bronnenlijst bij het lemma')),
                ('boek', models.TextField(blank=True, db_index=True, null=True, verbose_name='Boekaanduiding')),
            ],
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stad', models.CharField(db_index=True, default='(unknown)', max_length=100, verbose_name='Dialectlocatie')),
                ('code', models.CharField(default='xxxxxx', max_length=6, verbose_name='Plaatscode (Kloeke)')),
                ('nieuw', models.CharField(db_index=True, default='xxxxxx', max_length=6, verbose_name='Plaatscode (Nieuwe Kloeke)')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij dialect')),
            ],
            options={
                'verbose_name_plural': 'Dialecten',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woord', models.CharField(db_index=True, default='(unknown)', max_length=100, verbose_name='Dialectopgave')),
                ('toelichting', models.TextField(blank=True, db_index=True, verbose_name='Toelichting')),
                ('aflevering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Aflevering')),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dialect')),
            ],
            options={
                'verbose_name_plural': 'Entries',
                'permissions': (('search_gloss', 'Can search/view/edit full entry details'),),
                'ordering': ['lemma', 'woord'],
            },
        ),
        migrations.CreateModel(
            name='EntryMijn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('dutch_name', models.CharField(max_length=50)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='HelpChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('searchable', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=50)),
                ('help_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deel', models.IntegerField(default=0, verbose_name='Deel')),
                ('sectie', models.IntegerField(blank=True, null=True, verbose_name='Sectie (optioneel)')),
                ('aflnum', models.IntegerField(default=0, verbose_name='Aflevering')),
                ('processed', models.CharField(blank=True, max_length=100, verbose_name='Verwerkt')),
                ('read', models.IntegerField(default=0, verbose_name='Gelezen')),
                ('skipped', models.IntegerField(default=0, verbose_name='Overgeslagen')),
                ('csv_file', models.FileField(upload_to='csv_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(db_index=True, default='(unknown)', max_length=100, verbose_name='Gloss voor dit lemma')),
            ],
        ),
        migrations.CreateModel(
            name='LemmaDescr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Description')),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Lemma')),
            ],
        ),
        migrations.CreateModel(
            name='Mijn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='(unknown)', max_length=100, verbose_name='Mijn')),
                ('locatie', models.CharField(default='(unknown)', max_length=100, verbose_name='Locatie')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij mijn')),
            ],
            options={
                'verbose_name_plural': 'Mijnen',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairtype', models.CharField(default='(unknown)', max_length=100, verbose_name='Soort reparatie')),
                ('status', models.TextField(default='idle', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.IntegerField(default=0, verbose_name='Gelezen')),
                ('skipped', models.IntegerField(default=0, verbose_name='Overgeslagen')),
                ('status', models.TextField(default='idle', verbose_name='Status')),
                ('method', models.CharField(default='(unknown)', max_length=100, verbose_name='Reading method')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Info')),
            ],
        ),
        migrations.CreateModel(
            name='Trefwoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woord', models.CharField(db_index=True, default='(unknown)', max_length=100, verbose_name='Trefwoord')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij trefwoord')),
            ],
            options={
                'verbose_name_plural': 'Trefwoorden',
            },
        ),
        migrations.AddField(
            model_name='lemma',
            name='lmdescr',
            field=models.ManyToManyField(through='dictionary.LemmaDescr', to='dictionary.Description'),
        ),
        migrations.AddField(
            model_name='entrymijn',
            name='mijn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Mijn'),
        ),
        migrations.AddField(
            model_name='entry',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Lemma'),
        ),
        migrations.AddField(
            model_name='entry',
            name='mijnlijst',
            field=models.ManyToManyField(db_index=True, through='dictionary.EntryMijn', to='dictionary.Mijn'),
        ),
        migrations.AddField(
            model_name='entry',
            name='trefwoord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Trefwoord'),
        ),
        migrations.AddField(
            model_name='aflevering',
            name='deel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Deel'),
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([('dialect', 'lemma', 'trefwoord', 'woord')]),
        ),
    ]
