# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models, transaction
import django.db.models.deletion

def adapt_db(apps, schema_editor):
    Lemma = apps.get_model("dictionary", "Lemma")
    # Adapt the lemma.gloss to lower case
    with transaction.atomic():
        for lemma in Lemma.objects.all():
            lemma.gloss = lemma.gloss.lower()
            lemma.save()



class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(adapt_db),
    ]
