# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20180808_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='descr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='kloeketoelichting',
            field=models.TextField(blank=True, verbose_name='Toelichting bij dialectopgave voor een bepaalde kloekelocatie'),
        ),
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([('dialect', 'lemma', 'trefwoord', 'woord'), ('lemma', 'aflevering')]),
        ),
    ]
