# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20180815_1405'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='description',
            name='dictionary__toelich_a32e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='description',
            name='dictionary__toelich_1b14eb_idx',
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['toelichting', 'bronnenlijst', 'boek'], name='descr_three'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['toelichting', 'bronnenlijst'], name='descr_two'),
        ),
    ]
