# Generated by Django 2.2 on 2021-08-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20201217_0955'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='description',
            name='dictionary__toelich_a32e26_idx',
        ),
        migrations.RemoveIndex(
            model_name='description',
            name='dictionary__toelich_1b14eb_idx',
        ),
        migrations.AlterField(
            model_name='aflevering',
            name='deel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deel_afleveringen', to='dictionary.Deel'),
        ),
        migrations.AlterField(
            model_name='status',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_statuses', to='dictionary.Info'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['toelichting', 'bronnenlijst', 'boek'], name='descr_three'),
        ),
        migrations.AddIndex(
            model_name='description',
            index=models.Index(fields=['toelichting', 'bronnenlijst'], name='descr_two'),
        ),
    ]
