# Generated by Django 2.2 on 2024-02-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_auto_20210802_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijn',
            name='point',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Coordinates'),
        ),
    ]
